services:
    oro_hangouts_call.placeholder.filter:
        class: Oro\Bundle\HangoutsCallBundle\Placeholder\PlaceholderFilter
        public: true
        arguments:
            - '@oro_config.user'
            - '@oro_ui.user_agent_provider'

    oro_hangouts_call.placeholder.calendar_event.filter:
        class: Oro\Bundle\HangoutsCallBundle\Placeholder\CalendarEventPlaceholderFilter
        public: true
        arguments:
            - '@oro_hangouts_call.placeholder.filter'
            - '@oro_entity.doctrine_helper'
            - '@oro_security.token_accessor'

    oro_hangouts_call.placeholder.call.filter:
        class: Oro\Bundle\HangoutsCallBundle\Placeholder\CallPlaceholderFilter
        public: true
        arguments:
            - '@oro_hangouts_call.placeholder.filter'
            - '@oro_entity.doctrine_helper'

    oro_hangouts_call.twig.hangoutscall_extension:
        class: Oro\Bundle\HangoutsCallBundle\Twig\OroHangoutsCallExtension
        public: false
        arguments:
            - '%oro_hangouts.initial_apps%'
        tags:
            - { name: twig.extension }

    oro_hangouts_call.type.use_hangout_checkbox:
        class: Oro\Bundle\HangoutsCallBundle\Form\UseHangoutCheckboxType
        tags:
            - { name: form.type, alias: oro_hangouts_call_use_hangout_checkbox_type }
